
[[dependencies]]
  branch = "master"
  name = "github.com/CloudyKit/jet"

[[dependencies]]
  name = "github.com/fsnotify/fsnotify"
  version = "^1.4.2"

[[dependencies]]
  branch = "master"
  name = "github.com/gosimple/slug"

[[dependencies]]
  branch = "master"
  name = "github.com/gregjones/httpcache"

[[dependencies]]
  branch = "master"
  name = "github.com/microcosm-cc/bluemonday"

[[dependencies]]
  branch = "master"
  name = "github.com/nicksnyder/go-i18n"

[[dependencies]]
  branch = "master"
  name = "github.com/russross/blackfriday"

[[dependencies]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[dependencies]]
  branch = "master"
  name = "gopkg.in/fsnotify.v1"
